=== Auginte/prototype-data-lib/src/lt/dinosy/datalib/dinosy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:d="http://aurelijus.banelis.lt/dinosy"
    targetNamespace="http://aurelijus.banelis.lt/dinosy"
    elementFormDefault="qualified">
    <xs:element name="dinosy" type="d:dinosyTag">
        <xs:key name="sourceId">
            <xs:selector xpath="d:sources/*"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="sourceParent" refer="d:sourceId">
            <xs:selector xpath="d:sources/*"/>
            <xs:field xpath="@parentId"/>
        </xs:keyref>
        <xs:keyref name="dataToSource" refer="d:sourceId">
            <xs:selector xpath="d:data/*"/>
            <xs:field xpath="@sourceId"/>
        </xs:keyref>
        <xs:key name="dataId">
            <xs:selector xpath="d:data/*"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="relationFrom" refer="d:dataId">
            <xs:selector xpath="d:relations/d:relation"/>
            <xs:field xpath="@from"/>
        </xs:keyref>
        <xs:keyref name="relationTo" refer="d:dataId">
            <xs:selector xpath="d:relations/d:relation"/>
            <xs:field xpath="@to"/>
        </xs:keyref>
        <xs:keyref name="representationToData" refer="d:dataId">
            <xs:selector xpath="d:representations/*"/>
            <xs:field xpath="@dataId"/>
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="dinosyTag">
        <xs:sequence>
            <xs:element name="sources" type="d:sourcesTag"/>
            <xs:element name="data" type="d:dataTag"/>
            <xs:element name="relations" type="d:relationsTag" minOccurs="0"/>
            <xs:element name="representations" type="d:representationsTag"/>
        </xs:sequence>
    </xs:complexType>

    <!-- General section -->
    <xs:complexType name="sectionTag">
        <xs:complexContent>
            <xs:extension base="xs:anyType">
                <xs:attribute name="since" type="d:version" default="1.1.1"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="version">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+\.\d+\.\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Sources -->
    <xs:complexType name="sourcesTag">
        <xs:complexContent>
            <xs:restriction base="d:sectionTag">
                <xs:sequence>
                    <xs:element name="project" type="d:projectTag" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="event" type="d:eventTag" minOccurs="0"/>
                        <xs:element name="model" type="d:modelTag" minOccurs="0"/>
                        <xs:element name="book" type="d:bookTag" minOccurs="0"/>
                        <xs:element name="internet" type="d:internetTag" minOccurs="0"/>
                        <xs:element name="okular" type="d:okularTag"/>
                        <xs:element name="dinosy" type="d:dinosySourceTag" minOccurs="0"/>
                    </xs:choice>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="sourceTag">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
                <xs:attribute name="parentId" type="xs:integer"/>
                <xs:attribute name="date" type="xs:dateTime" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="projectTag">
        <xs:simpleContent>
            <xs:extension base="d:sourceTag">
                <xs:attribute name="address" type="xs:string"/>
                <xs:attribute name="owner" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="eventTag">
        <xs:simpleContent>
            <xs:extension base="d:sourceTag">
                <xs:attribute name="place" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="modelTag">
        <xs:simpleContent>
            <xs:extension base="d:sourceTag">
                <xs:attribute name="language" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="php"/>
                            <xs:enumeration value="java"/>
                            <xs:enumeration value="c++"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="bookTag">
        <xs:simpleContent>
            <xs:extension base="d:sourceTag">
                <xs:attribute name="page" type="xs:nonNegativeInteger" use="required"/>
                <xs:attribute name="isbn">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{9}[\d|x]"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="okularTag">
        <xs:simpleContent>
            <xs:extension base="d:bookTag">
                <xs:attribute name="position">
                    <xs:simpleType>
                        <xs:list itemType="xs:float"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="internetTag">
        <xs:simpleContent>
            <xs:extension base="d:sourceTag">
                <xs:attribute name="xpath" type="xs:string"/>
                <xs:attribute name="title" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="dinosySourceTag">
        <xs:simpleContent>
            <xs:extension base="xs:anySimpleType">
                <xs:attribute name="type" default="include">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="include"/>
                            <xs:enumeration value="link"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Data -->
    <xs:complexType name="dataTag">
        <xs:complexContent >
            <xs:restriction base="d:sectionTag">
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="plain" type="d:dataElementTag"/>
                    <xs:element name="link" type="d:linkDataTag"/>
                    <xs:element name="image" type="d:imageDataTag"/>
                    <xs:element name="class" type="d:classDataTag"/>
                </xs:choice>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:attributeGroup name="dataElementAttributes">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="parent" type="xs:integer" default="-1"/>
        <xs:attribute name="sourceId" type="xs:positiveInteger" use="required"/>
    </xs:attributeGroup>
    <xs:complexType name="dataElementTag">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attributeGroup ref="d:dataElementAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="classDataTag">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="extend" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="implement" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="attribute" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="method" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attributeGroup ref="d:dataElementAttributes"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="linkDataTag">
        <xs:simpleContent>
            <xs:extension base="d:dataElementTag">
                <xs:attribute name="url" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\w+://[^\s]+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="imageDataTag">
        <xs:simpleContent>
            <xs:extension base="d:dataElementTag">
                <xs:attribute name="cached" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Relations -->
    <xs:complexType name="relationsTag">
        <xs:complexContent>
            <xs:restriction base="d:sectionTag">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="generalization" type="d:relationTag"/>
                    <xs:element name="association" type="d:associantionTag"/>
                </xs:choice>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:attributeGroup name="relationAttributes">
        <xs:attribute name="from" type="xs:integer" use="required"/>
        <xs:attribute name="to" type="xs:integer" use="required"/>
    </xs:attributeGroup>
    <xs:complexType name="relationTag">
        <xs:complexContent>
            <xs:extension base="xs:anyType">
                <xs:attributeGroup ref="d:relationAttributes"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="associantionTag">
        <xs:complexContent>
            <xs:restriction base="d:relationTag">
                <xs:sequence>
                    <xs:element name="arrowTo" type="xs:string"/>
                </xs:sequence>
                <xs:attributeGroup ref="d:relationAttributes"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

    <!-- Representation -->
    <xs:complexType name="representationsTag">
        <xs:complexContent>
            <xs:restriction base="d:sectionTag">
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="element" type="d:representationTag"/>
                    <xs:element name="placeholder" type="d:placeHolderTag"/>
                </xs:choice>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="placeHolderTag">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:attribute name="dataId" type="xs:positiveInteger" use="required"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="representationTag">
        <xs:complexContent>
            <xs:extension base="d:placeHolderTag">
                <xs:sequence>
                    <xs:element name="position" type="d:positionType"/>
                    <xs:element name="size" type="d:sizeType"/>
                </xs:sequence>
                <xs:attribute name="mainIdea" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="positionType">
        <xs:restriction base="xs:string">
            <xs:pattern value="-?\d+\.?\d*\s-?\d+\.?\d*\s\d+\.?\d*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+\.?\d*\s\d+\.?\d*"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Auginte/prototype-data-lib/src/lt/dinosy/datalib/testdocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:dinosy xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:d='http://aurelijus.banelis.lt/dinosy'
   xsi:schemaLocation='http://aurelijus.banelis.lt/dinosy file:/home/aurelijus/Documents/DiNoSy/DataLib/src/lt/dinosy/datalib/dinosy.xsd'>
   <d:sources>
       <d:project id="6" date="2008-05-03T00:12:13" address="/home/lampp/htdocs/afigena.info/" owner="Aurelijus Banelis">WapSite.lt</d:project>
       <d:book id="1" date="2011-04-03T00:00:00" page="15">Ka≈ækokia knyga</d:book>
       <d:internet id="2" date="2010-05-03T00:12:14" parentId="1">http://wapsite.lt</d:internet>
       <d:event id="3" date="2010-05-03T18:12:14" place="Namai"/>
       <d:model id="4" date="2010-05-03T18:12:18" language="php" parentId="6">_system/labas.php</d:model>
       <d:model id="5" date="2010-05-04T18:12:18" language="php" parentId="6">_system/ate.php</d:model>
   </d:sources>
    <d:data since="1.2.3">
        <d:plain id="1" sourceId="1">Vienas</d:plain>
        <d:class id="2" sourceId="4">
            <d:name>Du</d:name>
            <d:attribute>+labas: String</d:attribute>
            <d:method>~hello(a: int): void</d:method>
        </d:class>
        <d:link id="3" sourceId="4" url="http://wapsite.lt">labas</d:link>
    </d:data>
    <d:relations>
        <d:relation from="1" to="2" type="generalization"/>
    </d:relations>
    <d:representations>
        <d:element dataId="1">
            <d:position>1 2 3</d:position>
            <d:size>10 20</d:size>
        </d:element>
        <d:element dataId="2">
            <d:position>3 4 5</d:position>
            <d:size>40 5</d:size>
        </d:element>
        <d:placeholder dataId="3"/>
    </d:representations>
</d:dinosy>
